title: 琪的弈
description: 人生如棋 记录琪的每一个脚印

url: http://weijingqi.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: weijingqi
   #twitter: brianmaierjr
   facebook: kekimail@gmail.com
   email: wei_jingqi@qq.com

google_analytics: "UA-63308610-1"
